#!/usr/bin/env sh

cd "$(dirname "$0")" || exit 1
args="$*"
args="${args%"${args##*[![:space:]]}"}"

if [ -n "$args" ]
then
  ./gradlew :qparrow-app:run --args="$args"
else
  ./gradlew :qparrow-app:run
fi
